import React, { useState } from 'react';
import { BlockMath, InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css';
import SectionLayout from '../../../components/content/SectionLayout.jsx';
import DefinitionBlock from '../../../components/content/DefinitionBlock.jsx';
import TheoremBlock from '../../../components/content/TheoremBlock.jsx';
import ExampleBlock from '../../../components/content/ExampleBlock.jsx';
import NoteBlock from '../../../components/content/NoteBlock.jsx';
import WarningBlock from '../../../components/content/WarningBlock.jsx';
import PythonCode from '../../../components/content/PythonCode.jsx';
import ReferenceList from '../../../components/content/ReferenceList.jsx';
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  Legend, ResponsiveContainer, AreaChart, Area,
} from 'recharts';

// Simulate regime-annotated returns
function generateRegimeData() {
  const data = [];
  let r = 100;
  for (let i = 0; i < 100; i++) {
    const regime = i < 30 ? 0 : i < 60 ? 1 : i < 80 ? 0 : 1;
    const mu    = regime === 0 ? 0.5 : -0.3;
    const sigma = regime === 0 ? 1.2 : 2.8;
    const ret   = mu + sigma * (Math.random() < 0.5 ? 1 : -1) * Math.abs(Math.random());
    r *= (1 + ret / 100);
    data.push({ t: i, price: +r.toFixed(2), regime, prob_bull: regime === 0 ? 0.8 + Math.random() * 0.2 : Math.random() * 0.3 });
  }
  return data;
}
const regimeData = generateRegimeData();

export default function RegimeDetection() {
  const [showRegimes, setShowRegimes] = useState(true);

  return (
    <SectionLayout
      title="Market Regime Detection"
      subject="Financial Forecasting"
      difficulty="advanced"
      readingTime={13}
    >
      <p>
        Financial markets switch between distinct states — bull vs bear, low vs high volatility, risk-on vs
        risk-off — and the optimal investment strategy differs dramatically across regimes. Regime detection
        models identify these states from observable data, enabling adaptive forecasting and portfolio management.
        The key challenge is that regimes are latent: they cannot be directly observed, only inferred.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">Hidden Markov Models</h2>

      <DefinitionBlock title="Hidden Markov Model for Market Regimes">
        An HMM models returns <InlineMath math="y_t" /> as being generated by a latent state
        <InlineMath math="s_t \in \{1, \ldots, K\}" /> that follows a first-order Markov chain:
        <BlockMath math="P(s_t = j | s_{t-1} = i) = A_{ij}" />
        Conditional on the state, returns are drawn from a state-specific distribution:
        <BlockMath math="y_t | s_t = k \sim \mathcal{N}(\mu_k, \sigma_k^2)" />
        Parameters <InlineMath math="\{A, \mu_k, \sigma_k\}" /> are estimated via the Baum-Welch
        algorithm (EM). The Viterbi algorithm then decodes the most likely state sequence.
      </DefinitionBlock>

      <div className="my-6 p-4 bg-gray-50 rounded-lg border">
        <h3 className="text-lg font-semibold mb-2">Simulated Price Path with Regime Detection</h3>
        <div className="flex items-center gap-4 mb-3">
          <button onClick={() => setShowRegimes(!showRegimes)}
            className={`px-3 py-1 text-sm rounded border ${showRegimes ? 'bg-blue-600 text-white' : 'border-gray-300'}`}>
            {showRegimes ? 'Hide Regimes' : 'Show Regimes'}
          </button>
          <span className="text-sm text-gray-600">
            <span className="inline-block w-3 h-3 bg-green-200 mr-1 rounded"></span>Bull regime
            <span className="inline-block w-3 h-3 bg-red-200 mr-1 rounded ml-3"></span>Bear regime
          </span>
        </div>
        <ResponsiveContainer width="100%" height={220}>
          <AreaChart data={regimeData} margin={{ top: 5, right: 20, bottom: 20, left: 10 }}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="t" label={{ value: 'Period', position: 'insideBottom', offset: -10 }} />
            <YAxis />
            <Tooltip />
            {showRegimes && (
              <Area dataKey="regime" fill="transparent" stroke="none"
                label={({ x, y }) => null} />
            )}
            <Line dataKey="price" stroke="#1d4ed8" strokeWidth={2} dot={false} name="Price" />
            <Line dataKey="prob_bull" stroke="#22c55e" strokeWidth={1.5} dot={false}
              yAxisId="right" strokeDasharray="4 2" name="P(Bull)" />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      <TheoremBlock title="Transition Matrix Interpretation">
        The transition matrix <InlineMath math="A" /> encodes regime persistence:
        <BlockMath math="A = \begin{pmatrix} p_{11} & 1-p_{11} \\ 1-p_{22} & p_{22} \end{pmatrix}" />
        Expected regime duration: <InlineMath math="\mathbb{E}[\text{duration}_k] = 1/(1-p_{kk})" />.
        A bull market with <InlineMath math="p_{11} = 0.97" /> has expected duration 1/0.03 ≈ 33 months.
        This matches historical bull market durations and allows scenario planning.
      </TheoremBlock>

      <h2 className="text-xl font-bold mt-6 mb-3">Volatility Regime Detection</h2>
      <p>
        Volatility regimes (low-vol vs high-vol) are more tractable than direction regimes because volatility
        is more persistent and estimable from high-frequency data. A 2-state GARCH model or realized volatility
        clustering identifies:
      </p>
      <ul className="list-disc ml-5 space-y-1 text-sm mt-2">
        <li><strong>Calm regime</strong>: VIX &lt; 20, daily returns ± 0.5–1%, momentum strategies perform</li>
        <li><strong>Crisis regime</strong>: VIX &gt; 30, daily returns ±2–5%, correlation spikes, diversification breaks</li>
      </ul>

      <h2 className="text-xl font-bold mt-6 mb-3">Clustering-Based Regime Detection</h2>
      <p>
        K-means and Gaussian Mixture Models (GMM) provide alternative unsupervised approaches. Feature
        engineering is critical: cluster on {'{'}rolling volatility, trend strength, cross-asset correlations,
        term structure slope{'}'} rather than raw returns.
      </p>

      <ExampleBlock title="Three-Regime Portfolio Allocation">
        An asset manager identifies three regimes using a 3-state HMM on global equity + bond + credit returns:
        <ul className="list-disc ml-5 mt-2 space-y-1 text-sm">
          <li><strong>Risk-On</strong> (p≈0.55): High equity allocation, momentum tilt, reduce bonds</li>
          <li><strong>Transition</strong> (p≈0.30): Balanced allocation, reduce concentration</li>
          <li><strong>Risk-Off</strong> (p≈0.15): Treasury bonds, gold, defensive equities, hedge</li>
        </ul>
        Regime-switching allocation improved Sharpe ratio from 0.52 (static 60/40) to 0.71 in backtest.
        Practical limitation: regime detection lags the true regime change by 2–6 weeks due to smoothing.
      </ExampleBlock>

      <h2 className="text-xl font-bold mt-6 mb-3">Regime-Switching ARIMA</h2>
      <p>
        Markov Switching ARIMA (MS-ARIMA) allows AR parameters and variance to switch with the hidden state.
        For return prediction, a 2-state model with different means and variances captures the bull/bear
        distinction. The Hamilton (1989) model is the canonical example.
      </p>

      <NoteBlock>
        HMMs are sensitive to initialization. Run the EM algorithm multiple times from different random
        starting points (at least 10–20 restarts) and select the solution with highest log-likelihood.
        Also cross-validate the number of states K using BIC or out-of-sample likelihood rather than
        in-sample fit — K=3 or K=4 often overfits.
      </NoteBlock>

      <WarningBlock>
        Regime detection has a fundamental look-ahead bias problem in backtesting. The HMM knows the
        full history when fitting, so identified regime boundaries look cleaner than they would in real
        time. Always evaluate regime-based strategies in true walk-forward (online) fashion — fitting
        only on data available at each decision point.
      </WarningBlock>

      <PythonCode
        title="HMM Market Regime Detection with hmmlearn"
        code={`import numpy as np
import pandas as pd
from hmmlearn import hmm
from sklearn.preprocessing import StandardScaler

# ── Generate or load return data ──────────────────────────────────────────────
np.random.seed(42)

# Simulate 2-regime returns: bull (high mean, low vol) + bear (low mean, high vol)
def simulate_regime_returns(n=1000):
    regimes  = [0]
    A = np.array([[0.97, 0.03], [0.05, 0.95]])   # transition matrix
    for _ in range(n - 1):
        r = regimes[-1]
        regimes.append(0 if np.random.rand() < A[r, 0] else 1)

    mus    = [0.05, -0.10]   # % per month
    sigmas = [1.20,  3.50]
    returns = np.array([np.random.normal(mus[s], sigmas[s]) for s in regimes])
    return returns, np.array(regimes)

returns, true_regimes = simulate_regime_returns(n=600)

# Feature engineering: returns + rolling vol
vol_21 = pd.Series(returns).rolling(21).std().fillna(method='bfill').values
features = np.column_stack([returns, vol_21])

# ── Fit 2-state Gaussian HMM ─────────────────────────────────────────────────
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(features)

best_model, best_score = None, -np.inf
for trial in range(15):    # multiple restarts
    model = hmm.GaussianHMM(
        n_components=2,
        covariance_type='full',
        n_iter=200,
        random_state=trial,
    )
    try:
        model.fit(X_scaled)
        score = model.score(X_scaled)
        if score > best_score:
            best_score = score
            best_model = model
    except Exception:
        continue

# ── Decode states ─────────────────────────────────────────────────────────────
states      = best_model.predict(X_scaled)
state_probs = best_model.predict_proba(X_scaled)   # shape (T, K)

# Identify which state is "bull" (higher mean return)
state_means = [returns[states == k].mean() for k in range(2)]
bull_state  = np.argmax(state_means)
bear_state  = 1 - bull_state

print(f"Bull state ({bull_state}): mean={state_means[bull_state]:.3f}%, "
      f"vol={returns[states == bull_state].std():.3f}%")
print(f"Bear state ({bear_state}): mean={state_means[bear_state]:.3f}%, "
      f"vol={returns[states == bear_state].std():.3f}%")

# ── Transition matrix ─────────────────────────────────────────────────────────
A = best_model.transmat_
print(f"\\nTransition Matrix:")
print(f"  P(bull→bull) = {A[bull_state, bull_state]:.3f}  "
      f"Expected duration: {1/(1-A[bull_state, bull_state]):.0f} periods")
print(f"  P(bear→bear) = {A[bear_state, bear_state]:.3f}  "
      f"Expected duration: {1/(1-A[bear_state, bear_state]):.0f} periods")

# ── Regime-adaptive Sharpe ratio ─────────────────────────────────────────────
# Strategy: invest in risky asset only in bull regime
bull_proba     = state_probs[:, bull_state]
threshold      = 0.6
position       = (bull_proba > threshold).astype(float)
strategy_ret   = position * returns
benchmark_ret  = returns   # always invested

def sharpe(rets, annualize=12):
    return rets.mean() / rets.std() * np.sqrt(annualize)

print(f"\\nBacktest Performance:")
print(f"  Buy & Hold Sharpe: {sharpe(benchmark_ret):.3f}")
print(f"  Regime Strategy Sharpe: {sharpe(strategy_ret):.3f}")
print(f"  % time in market: {position.mean():.1%}")

# ── 3-state model comparison ───────────────────────────────────────────────────
bic_scores = {}
for k in [2, 3, 4]:
    m = hmm.GaussianHMM(n_components=k, covariance_type='full', n_iter=200, random_state=0)
    try:
        m.fit(X_scaled)
        n_params = k**2 + k * X_scaled.shape[1] + k * (X_scaled.shape[1]**2)
        bic = -2 * m.score(X_scaled) * len(X_scaled) + n_params * np.log(len(X_scaled))
        bic_scores[k] = round(bic, 1)
    except Exception:
        bic_scores[k] = None

print("\\nBIC by number of states (lower = better):")
for k, b in bic_scores.items():
    print(f"  K={k}: BIC={b}")
`}
      />

      <ReferenceList
        references={[
          {
            author: 'Hamilton, J.D.',
            year: 1989,
            title: 'A new approach to the economic analysis of nonstationary time series and the business cycle',
            journal: 'Econometrica',
            volume: '57(2)',
            pages: '357–384',
          },
          {
            author: 'Ang, A. & Bekaert, G.',
            year: 2002,
            title: 'Regime switches in interest rates',
            journal: 'Journal of Business & Economic Statistics',
            volume: '20(2)',
            pages: '163–182',
          },
        ]}
      />
    </SectionLayout>
  );
}
